routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login'); //redirect ke halaman login
});

Auth::routes();

//FEATURES
Route::resource('kelola_user', App\Http\Controllers\Features\KelolaUserController::class);
// pelatihan
Route::resource('pelatihan', App\Http\Controllers\Features\PelatihanController::class);
// jadwal pelatihan
Route::resource('jadwal', App\Http\Controllers\Features\JadwalPelatihanController::class);
// Materi
Route::resource('kelola_materi', App\Http\Controllers\Features\KelolaMateriController::class);
//user pelatihan
Route::post('pelatihan_user/user_register/{id}', [App\Http\Controllers\Features\PelatihanUserController::class, 'user_register'])->name('pelatihan_user.user_register');
Route::resource('pelatihan_user', App\Http\Controllers\Features\PelatihanUserController::class);
//user materi
Route::get('materi_user', [App\Http\Controllers\Features\MateriUserController::class, 'index'])->name('materi_user.index');
Route::get('materi_user/{id}', [App\Http\Controllers\Features\MateriUserController::class, 'show'])->name('materi_user.show');
Route::get('materi_user/{id}/detail', [App\Http\Controllers\Features\MateriUserController::class, 'detail'])->name('materi_user.detail');
//kehadiran user
Route::post('kehadiran_user', [App\Http\Controllers\Features\KehadiranUserController::class, 'store'])->name('kehadiran_user.store');
//komentar user
Route::post('komentar_user', [App\Http\Controllers\Features\KomentarUserController::class, 'store'])->name('komentar_user.store');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
// admin

Route::group(['middleware' => ['auth', 'admin']], function () {
    Route::get('admin/dashboard', function () {
        return view('dashboard/index');
    })->name('admin.dashboard');

    Route::get('admin/profile', function () {
        return "Admin Profile";
    })->name('admin.profile');
});

// mentor
Route::group(['middleware' => ['auth']], function () {
    Route::get('mentor/dashboard', function () {
        return view('dashboard/index');
    })->name('mentor.dashboard');
});

// user
Route::group(['middleware' => ['auth']], function () {
    Route::get('user/dashboard', function () {
        return view('dashboard/index');
    })->name('user.dashboard');
});

app/Http/Controllers/Features/PelatihanUserController.php
<?php

namespace App\Http\Controllers\Features;

use App\Http\Controllers\Controller;
use App\Models\Pelatihan;
use App\Models\User;
use App\Models\UserRegisPelatihan;
use Illuminate\Http\Request;

class PelatihanUserController extends Controller
{
    public function index()
    {
        $pelatihan = Pelatihan::all();
        return view('pelatihan_user.index', compact('pelatihan'));
    }

    public function user_register(Request $request, $id)
    {
        //validasi
        $request->validate([
            'id_pelatihan' => 'required',
        ]);
        //cek apakah sudah daftar
        $cek = UserRegisPelatihan::where('id_pelatihan', $id)->where('id_users', auth()->user()->id)->first();
        if ($cek) {
            return back()->with('error', 'Anda sudah mendaftar pelatihan ini');
        }
        //simpan ke user_regis_pelatihan
        UserRegisPelatihan::create([
            'id_pelatihan' => $id,
            'id_users' => auth()->user()->id
        ]);
        return back()->with('success', 'Berhasil mendaftar pelatihan');
    }
}

resources/views/pelatihan_user/create.blade.php
@extends('layouts.app-main')

@section('content')
    <div class="row">
        <div class="col-12">

            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Tambah Data Pelatihan</h6>
                </div>
                <div class="card-body">
                    <form action="{{ route('pelatihan.store') }}" method="post">
                        @csrf
                        
                        <div class="form-group row">
                            <label for="inputNama" class="col-sm-3 col-form-label">Nama Pelatihan</label>
                            <div class="col-sm-9">
                                <input type="text"
                                    class="form-control @error('name')
                                    is-invalid
                                    @enderror"
                                    
                                    @error('name')
                                    autofocus
                                    @enderror
                                    id="inputNama" name="name" placeholder="Nama">
                            </div>
                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group row">
                            <label for="deskripsi" class="col-sm-3 col-form-label">Deskripsi</label>
                            <div class="col-sm-9">
                                <input type="deskripsi"
                                    class="form-control @error('deskripsi')
                                    is-invalid
                                    @enderror"

                                    @error('deskripsi')
                                    autofocus
                                    @enderror
                                    id="inputdeskripsi3" name="deskripsi" placeholder="deskripsi">
                            </div>
                            @error('deskripsi')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group row">
                            <label for="inputTgl" class="col-sm-3 col-form-label">Tanggal Pelatihan</label>
                            <div class="col-sm-9">
                                <input type="date"
                                    class="form-control @error('tanggal_pelatihan')
                                    is-invalid
                                    @enderror"
                                    
                                    @error('tanggal_pelatihan')
                                    autofocus
                                    @enderror
                                    id="inputTgl" name="tanggal_pelatihan" placeholder="Tanggal Pelatihan" >
                            </div>
                            @error('tanggal_pelatihan')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Simpan</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    @push('script')
    @endpush
@endsection

resources/views/pelatihan_user/edit.blade.php
@extends('layouts.app-main')

@section('content')
    <div class="row">
        <div class="col-12">

            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Edit Data Pelatihan</h6>
                </div>
                <div class="card-body">
                    <form action="{{ route('pelatihan.update', $pelatihan->id) }}" method="post">
                        @csrf
                        @method('PUT')
                        
                        <div class="form-group row">
                            <label for="inputNama" class="col-sm-3 col-form-label">Nama Pelatihan</label>
                            <div class="col-sm-9">
                                <input type="text"
                                    class="form-control @error('name')
                                    is-invalid
                                    @enderror"
                                    value="{{ $pelatihan->name }}"
                                    @error('name')
                                    autofocus
                                    @enderror
                                    id="inputNama" name="name" placeholder="Nama">
                            </div>
                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group row">
                            <label for="deskripsi" class="col-sm-3 col-form-label">Deskripsi</label>
                            <div class="col-sm-9">
                                <input type="deskripsi"
                                    class="form-control @error('deskripsi')
                                    is-invalid
                                    @enderror"
                                    value="{{ $pelatihan->deskripsi }}"
                                    @error('deskripsi')
                                    autofocus
                                    @enderror
                                    id="inputdeskripsi3" name="deskripsi" placeholder="deskripsi">
                            </div>
                            @error('deskripsi')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group row">
                            <label for="inputTgl" class="col-sm-3 col-form-label">Tanggal Pelatihan</label>
                            <div class="col-sm-9">
                                <input type="date"
                                    class="form-control @error('tanggal_pelatihan')
                                    is-invalid
                                    @enderror"
                                    value="{{ $pelatihan->tanggal_pelatihan }}"
                                    @error('tanggal_pelatihan')
                                    autofocus
                                    @enderror
                                    id="inputTgl" name="tanggal_pelatihan" placeholder="Tanggal Pelatihan" >
                            </div>
                            @error('tanggal_pelatihan')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        

                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Simpan</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    @push('script')
    @endpush
@endsection

resources/views/pelatihan_user/index.blade.php
@extends('layouts.app-main')

@section('content')
    <div class="row">
        <div class="col-12 stretch-card transparent">
            <div class="card">
                <div class="card-header">{{ __('Daftar Pelatihan') }}</div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="col-md-12 grid-margin transparent">
                        <div class="row">
                            @foreach ($pelatihan as $item)
                            <div class="col-md-6 mb-4 stretch-card transparent">
                                <div class="card card-tale">
                                    <div class="card-body">
                                        <p class="mb-4">Pelatihan</p>
                                        <p class="fs-30 mb-2">{{ $item->name ?? '' }}</p>
                                        <p>{{ $item->tanggal_pelatihan ?? '' }}</p>
                                        
                                        <form action="{{ route('pelatihan_user.user_register', $item->id) }}" method="POST">
                                            @csrf
                                            <input type="hidden" name="id_pelatihan" value="{{ $item->id }}">
                                            <button type="submit" class="btn btn-primary">Klik untuk mendaftar(abaikan jika sudah mendaftar)</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            @endforeach
                        </div>    
                    </div>
                </div>
            </div>
        </div>
    </div>
    @push('script')
        <script>
            $(document).ready(function() {
                var table = $('#dataTable').DataTable({
                    processing: true,
                    ajax: {
                        url: "{{ route('pelatihan.index') }}",
                    },
                    serverSide: true,
                    columnDefs: [{
                        "defaultContent": "-",
                        "targets": "_all"
                    }, ],
                    columns: [{
                            data: 'id',
                            name: 'id',
                            orderable: false,
                            searchable: false
                        },
                        {
                            data: 'name',
                            name: 'name'
                        },
                        {
                            data: 'deskripsi',
                            name: 'deskripsi'
                        },
                        {
                            data: 'tanggal_pelatihan',
                            name: 'tanggal_pelatihan'
                        },
                        {
                            data: 'action',
                        }

                    ],
                    dom: 'Bfrtip',
                    buttons: [
                        'pdf', 'excel', 'print',
                    ]
                });
            });
        </script>
    @endpush
@endsection