routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login'); //redirect ke halaman login
});

Auth::routes();

//FEATURES
Route::resource('kelola_user', App\Http\Controllers\Features\KelolaUserController::class);
// pelatihan
Route::resource('pelatihan', App\Http\Controllers\Features\PelatihanController::class);
// jadwal pelatihan
Route::resource('jadwal', App\Http\Controllers\Features\JadwalPelatihanController::class);
// Materi
Route::resource('kelola_materi', App\Http\Controllers\Features\KelolaMateriController::class);
//user pelatihan
Route::post('pelatihan_user/user_register/{id}', [App\Http\Controllers\Features\PelatihanUserController::class, 'user_register'])->name('pelatihan_user.user_register');
Route::resource('pelatihan_user', App\Http\Controllers\Features\PelatihanUserController::class);
//user materi
Route::get('materi_user', [App\Http\Controllers\Features\MateriUserController::class, 'index'])->name('materi_user.index');
Route::get('materi_user/{id}', [App\Http\Controllers\Features\MateriUserController::class, 'show'])->name('materi_user.show');
Route::get('materi_user/{id}/detail', [App\Http\Controllers\Features\MateriUserController::class, 'detail'])->name('materi_user.detail');
//kehadiran user
Route::post('kehadiran_user', [App\Http\Controllers\Features\KehadiranUserController::class, 'store'])->name('kehadiran_user.store');
//komentar user
Route::post('komentar_user', [App\Http\Controllers\Features\KomentarUserController::class, 'store'])->name('komentar_user.store');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
// admin

Route::group(['middleware' => ['auth', 'admin']], function () {
    Route::get('admin/dashboard', function () {
        return view('dashboard/index');
    })->name('admin.dashboard');

    Route::get('admin/profile', function () {
        return "Admin Profile";
    })->name('admin.profile');
});

// mentor
Route::group(['middleware' => ['auth']], function () {
    Route::get('mentor/dashboard', function () {
        return view('dashboard/index');
    })->name('mentor.dashboard');
});

// user
Route::group(['middleware' => ['auth']], function () {
    Route::get('user/dashboard', function () {
        return view('dashboard/index');
    })->name('user.dashboard');
});

app/Models/JadwalPelatihan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class JadwalPelatihan extends Model
{
    use HasFactory;

    protected $table = 'jadwal_pelatihans';
    protected $guarded = [];

    public function pelatihan()
    {
        return $this->belongsTo(Pelatihan::class, 'id_pelatihan', 'id');
    }

    public function mentor()
    {
        return $this->belongsTo(User::class, 'id_user', 'id');
    }
}

app/Http/Controllers/Features/JadwalPelatihanController.php
<?php

namespace App\Http\Controllers\Features;

use App\Http\Controllers\Controller;
use App\Models\JadwalPelatihan;
use App\Models\Pelatihan;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class JadwalPelatihanController extends Controller
{
    public function index()
    {
        if (request()->ajax()) {
            $data = JadwalPelatihan::with('pelatihan', 'mentor')->get();
            return \DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('pelatihan', function ($row) {
                    return $row->pelatihan->name;
                })
                ->addColumn('mentor', function ($row) {
                    return $row->mentor->name;
                })
                ->addColumn('action', function ($row) {
                    $action = ' <form action="' . route('jadwal.destroy', $row->id) . '" method="POST" class="d-inline">';
                    $action .= csrf_field();
                    $action .= method_field('DELETE');
                    $action .= ' <button type="submit" class="btn btn-danger btn-sm btn-delete">Delete</button>';
                    $action .= '</form>';

                    return $action;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('jadwal_pelatihan.index');
    }

    public function create()
    {
        $mentor = User::where('jabatan', 'mentor')->get();
        $pelatihan = Pelatihan::all();
        return view('jadwal_pelatihan.create', compact('mentor', 'pelatihan'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'id_pelatihan' => 'required|unique:jadwal_pelatihans,id_pelatihan',
            'id_user' => 'required',
        ]);

        JadwalPelatihan::create($request->all());

        return redirect()->route('jadwal.index')
            ->with('success', 'Pelatihan created successfully.');
    }

    public function destroy($id)
    {
        JadwalPelatihan::where('id', $id)->delete();

        return redirect()->route('jadwal.index')
            ->with('success', 'Pelatihan deleted successfully');
    }
}

resources/views/jadwal_pelatihan/create.blade.php
@extends('layouts.app-main')

@section('content')
    <div class="row">
        <div class="col-12">

            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Edit Data User</h6>
                </div>
                <div class="card-body">
                    <form action="{{ route('jadwal.store') }}" method="post">
                        @csrf
                        
                        <div class="form-group row">
                            <label for="inputNama" class="col-sm-3 col-form-label">Nama Pelatihan</label>
                            <div class="col-sm-9">
                                <select class="form-control @error('name')
                                is-invalid
                                @enderror" name="id_pelatihan" id="inputNama">
                                    <option value="">Pilih Pelatihan</option>
                                    @foreach ($pelatihan as $item)
                                        <option value="{{ $item->id }}">{{ $item->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            @error('id_pelatihan')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                       
                        <div class="form-group row">
                            <label for="inputTgl" class="col-sm-3 col-form-label">Mentor</label>
                            <div class="col-sm-9">
                                <select class="form-control @error('id_user')
                                is-invalid
                                @enderror" name="id_user" id="inputTgl">
                                    <option value="">Pilih Mentor</option>
                                    @foreach ($mentor as $item)
                                        <option value="{{ $item->id }}">{{ $item->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            @error('id_user')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Simpan</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    @push('script')
    @endpush
@endsection

resources/views/jadwal_pelatihan/edit.blade.php
@extends('layouts.app-main')

@section('content')
    <div class="row">
        <div class="col-12">

            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Edit Data Pelatihan</h6>
                </div>
                <div class="card-body">
                    <form action="{{ route('pelatihan.update', $pelatihan->id) }}" method="post">
                        @csrf
                        @method('PUT')
                        
                        <div class="form-group row">
                            <label for="inputNama" class="col-sm-3 col-form-label">Nama Pelatihan</label>
                            <div class="col-sm-9">
                                <input type="text"
                                    class="form-control @error('name')
                                    is-invalid
                                    @enderror"
                                    value="{{ $pelatihan->name }}"
                                    @error('name')
                                    autofocus
                                    @enderror
                                    id="inputNama" name="name" placeholder="Nama">
                            </div>
                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group row">
                            <label for="deskripsi" class="col-sm-3 col-form-label">Deskripsi</label>
                            <div class="col-sm-9">
                                <input type="deskripsi"
                                    class="form-control @error('deskripsi')
                                    is-invalid
                                    @enderror"
                                    value="{{ $pelatihan->deskripsi }}"
                                    @error('deskripsi')
                                    autofocus
                                    @enderror
                                    id="inputdeskripsi3" name="deskripsi" placeholder="deskripsi">
                            </div>
                            @error('deskripsi')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group row">
                            <label for="inputTgl" class="col-sm-3 col-form-label">Tanggal Pelatihan</label>
                            <div class="col-sm-9">
                                <input type="date"
                                    class="form-control @error('tanggal_pelatihan')
                                    is-invalid
                                    @enderror"
                                    value="{{ $pelatihan->tanggal_pelatihan }}"
                                    @error('tanggal_pelatihan')
                                    autofocus
                                    @enderror
                                    id="inputTgl" name="tanggal_pelatihan" placeholder="Tanggal Pelatihan" >
                            </div>
                            @error('tanggal_pelatihan')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        

                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Simpan</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    @push('script')
    @endpush
@endsection

resources/views/jadwal_pelatihan/index.blade.php
@extends('layouts.app-main')

@section('content')
    <div class="row">
        <div class="col-12 stretch-card transparent">
            <div class="card">
                <div class="card-header">{{ __('Kelola Data Jadwal Mentor') }}</div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-primary">Data Jadwal Mentor</h6>
                    </div>
                    <div class="table-responsive p-3">
                        <a href="{{ route('jadwal.create')}}" class="btn btn-primary"> Tambah Jadwal Pelatihan Mentor</a>
                        <table class="table align-items-center table-flush" id="dataTable">
                            <thead class="thead-light">
                                <tr>
                                    <th>No</th>
                                    <th>Pelatihan</th>
                                    <th>Mentor</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @push("script")
    <script>
        $(document).ready(function() {
            var table = $('#dataTable').DataTable({
                processing: true,
                ajax: {
                    url: "{{ route('jadwal.index') }}",
                },
                serverSide: true,
                columnDefs: [{
                    "defaultContent": "-",
                    "targets": "_all"
                }, ],
                columns: [{
                        data: 'id',
                        name: 'id',
                        orderable: false,
                        searchable: false
                    },
                    {
                        data: 'pelatihan',
                        name: 'pelatihan'
                    },
                    {
                        data: 'mentor',
                        name: 'mentor'
                    },
                    {
                        data: 'action',
                    }

                ],
                dom: 'Bfrtip',
                    buttons: [
                        'pdf','excel', 'print',
                    ]
            });
        });
    </script>

    @endpush
@endsection