routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login'); //redirect ke halaman login
});

Auth::routes();

//FEATURES
Route::resource('kelola_user', App\Http\Controllers\Features\KelolaUserController::class);
// pelatihan
Route::resource('pelatihan', App\Http\Controllers\Features\PelatihanController::class);
// jadwal pelatihan
Route::resource('jadwal', App\Http\Controllers\Features\JadwalPelatihanController::class);
// Materi
Route::resource('kelola_materi', App\Http\Controllers\Features\KelolaMateriController::class);
//user pelatihan
Route::post('pelatihan_user/user_register/{id}', [App\Http\Controllers\Features\PelatihanUserController::class, 'user_register'])->name('pelatihan_user.user_register');
Route::resource('pelatihan_user', App\Http\Controllers\Features\PelatihanUserController::class);
//user materi
Route::get('materi_user', [App\Http\Controllers\Features\MateriUserController::class, 'index'])->name('materi_user.index');
Route::get('materi_user/{id}', [App\Http\Controllers\Features\MateriUserController::class, 'show'])->name('materi_user.show');
Route::get('materi_user/{id}/detail', [App\Http\Controllers\Features\MateriUserController::class, 'detail'])->name('materi_user.detail');
//kehadiran user
Route::post('kehadiran_user', [App\Http\Controllers\Features\KehadiranUserController::class, 'store'])->name('kehadiran_user.store');
//komentar user
Route::post('komentar_user', [App\Http\Controllers\Features\KomentarUserController::class, 'store'])->name('komentar_user.store');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
// admin

Route::group(['middleware' => ['auth', 'admin']], function () {
    Route::get('admin/dashboard', function () {
        return view('dashboard/index');
    })->name('admin.dashboard');

    Route::get('admin/profile', function () {
        return "Admin Profile";
    })->name('admin.profile');
});

// mentor
Route::group(['middleware' => ['auth']], function () {
    Route::get('mentor/dashboard', function () {
        return view('dashboard/index');
    })->name('mentor.dashboard');
});

// user
Route::group(['middleware' => ['auth']], function () {
    Route::get('user/dashboard', function () {
        return view('dashboard/index');
    })->name('user.dashboard');
});

app/Http/Controllers/Features/KelolaUserController.php
<?php

namespace App\Http\Controllers\Features;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class KelolaUserController extends Controller
{
    public function index()
    {
        if (request()->ajax()) {
            $user = User::all();
            return \DataTables::of($user)
                ->addIndexColumn()

                ->addColumn('action', function ($row) {
                    $action = ' <a class="btn btn-primary btn-sm" href="' . route('kelola_user.edit', $row->id) . '">Edit</a>';
                    $action .= ' <form action="' . route('kelola_user.destroy', $row->id) . '" method="POST" class="d-inline">';
                    $action .= csrf_field();
                    $action .= method_field('DELETE');
                    $action .= ' <button type="submit" class="btn btn-danger btn-sm btn-delete">Delete</button>';
                    $action .= '</form>';

                    return $action;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('kelola_user.index');
    }

    public function edit($id)
    {
        $user = User::findOrFail($id);
        return view('kelola_user.edit', compact('user'));
    }

    public function update (Request $request, $id)
    {
        $validated = $request->validate([
            'name' => 'required',
            'email' => 'required',
            'tgl_lahir' => 'required',
            'alamat' => 'required',
        ]);
        $user = User::findOrFail($id);
        $data = [
            'name' => $request->name,
            'email' => $request->email,
            'tgl_lahir' => $request->tgl_lahir,
            'alamat' => $request->alamat,
        ];
        if ($request->password) {
            $validated = $request->validate([
                'password' => 'required|min:8',
            ]);
            $data['password'] = bcrypt($request->password);
        }
        $user->update($data);

        return redirect()->route('kelola_user.index')->with('success', 'Data berhasil diupdate');
    }

    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();
        return redirect()->back()->with('success', 'Data berhasil dihapus');
    }
}

resources/views/kelola_user/edit.blade.php
@extends('layouts.app-main')

@section('content')
    <div class="row">
        <div class="col-12">

            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Edit Data User</h6>
                </div>
                <div class="card-body">
                    <form action="{{ route('kelola_user.update', $user->id) }}" method="post">
                        @csrf
                        @method('PUT')
                        
                        <div class="form-group row">
                            <label for="inputNama" class="col-sm-3 col-form-label">Nama</label>
                            <div class="col-sm-9">
                                <input type="text"
                                    class="form-control @error('nip')
                                    is-invalid
                                    @enderror"
                                    value="{{ old('name', $user->name) }}"
                                    @error('name')
                                    autofocus
                                    @enderror
                                    id="inputNama" name="name" placeholder="Nama">
                            </div>
                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-3 col-form-label">Email</label>
                            <div class="col-sm-9">
                                <input type="email"
                                    class="form-control @error('email')
                                    is-invalid
                                    @enderror"
                                    value="{{ old('email', $user->email) }}"
                                    @error('email')
                                    autofocus
                                    @enderror
                                    id="inputEmail3" name="email" placeholder="Email">
                            </div>
                            @error('email')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group row">
                            <label for="inputTgl" class="col-sm-3 col-form-label">Tanggal Lahir</label>
                            <div class="col-sm-9">
                                <input type="date"
                                    class="form-control @error('tgl_lahir')
                                    is-invalid
                                    @enderror"
                                    value="{{ old('tgl_lahir', $user->tgl_lahir) }}"
                                    @error('tgl_lahir')
                                    autofocus
                                    @enderror
                                    id="inputTgl" name="tgl_lahir" placeholder="Tanggal lahir" >
                            </div>
                            @error('tgl_lahir')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group row">
                            <label for="inputAlamat" class="col-sm-3 col-form-label">Alamat</label>
                            <div class="col-sm-9">
                                <input type="textarea"
                                    class="form-control @error('alamat')
                                    is-invalid
                                    @enderror"
                                    value="{{ old('alamat', $user->alamat) }}"
                                    @error('alamat')
                                    autofocus
                                    @enderror
                                    id="inputAlamat" name="alamat" placeholder="Alamat" >
                            </div>
                            @error('alamat')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        
                        <div class="form-group row">
                            <label for="inputPassword3" class="col-sm-3 col-form-label">Password</label>
                            <div class="col-sm-9">
                                <input type="password" class="form-control" id="inputPassword3" name="password"
                                    placeholder="Password">
                            </div>
                        </div>
                        

                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Simpan</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    @push('script')
    @endpush
@endsection

resources/views/kelola_user/index.blade.php
@extends('layouts.app-main')

@section('content')
    <div class="row">
        <div class="col-12 stretch-card transparent">
            <div class="card">
                <div class="card-header">{{ __('Kelola Data User') }}</div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-primary">Data User</h6>
                    </div>
                    <div class="table-responsive p-3">
                        {{-- <a href="{{ route('kelola_user.create')}}" class="btn btn-primary"> Tambah User</a> --}}
                        <table class="table align-items-center table-flush" id="dataTable">
                            <thead class="thead-light">
                                <tr>
                                    <th>No</th>
                                    <th>Nama</th>
                                    <th>Email</th>
                                    <th>Alamat</th>
                                    <th>Tgl Lahir</th>
                                    <th>Jabatan</th>
                                    <th>Role</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @push("script")
    <script>
        $(document).ready(function() {
            var table = $('#dataTable').DataTable({
                processing: true,
                ajax: {
                    url: "{{ route('kelola_user.index') }}",
                },
                serverSide: true,
                columnDefs: [{
                    "defaultContent": "-",
                    "targets": "_all"
                }, ],
                columns: [{
                        data: 'id',
                        name: 'id',
                        orderable: false,
                        searchable: false
                    },
                    {
                        data: 'name',
                        name: 'name'
                    },
                    {
                        data: 'email',
                        name: 'email'
                    },
                    {
                        data: 'alamat',
                        name: 'alamat'
                    },
                    {
                        data: 'tgl_lahir',
                        name: 'tgl_lahir'
                    },
                    {
                        data: 'jabatan',
                        name: 'jabatan'
                    },
                    {
                        data: 'role',
                        name: 'role'
                    },
                    {
                        data: 'action',
                    }

                ],
                dom: 'Bfrtip',
                    buttons: [
                        'pdf','excel', 'print',
                    ]
            });
        });
    </script>

    @endpush
@endsection